### ISSUE TITLE
Shall I add a number of extra layers from NEON h5 data?

### ISSUE THREAD

**Issue by MarconiS** [weecology/NeonSpeciesBenchmark#2]
NEON AOP hyper spectral data has a bunch of useful ancillary information that can be extracted from the .h5 (e.g. elevation and sensor angle). I am happy to tweak hyperspectral.py with an extra function that queries the .h5 and saves the tif files upon request.

**Comment by bw4sz** [comment]
No, I think the current metadata is good.
